# You must store workflow files in the .github/workflows directory of your repository.
#h ttps://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# GitHub displays the names of your workflows on your repository's actions page
name: Bootcamp Action! 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches-ignore:    
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
    - main
    - 'feature/**'
  label:
    types:
      - created
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ghhandle:
        description: 'The GitHub Handle of the user to set up'
        default: 'mygithubhandle'
        type: string
        
   # callout cron schedule - cron: '30 5 * * 1,3'
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  builddabootcamp:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! ${{ github.event.inputs.ghhandle }}

